---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 2
  require_ruby_for_busser: false
  require_chef_for_busser: true
  requirements_path: "./requirements.yml"
  hosts: all

platforms:
  - name: ubuntu-14-docker
    driver_config:
      image: geerlingguy/docker-ubuntu1404-ansible:latest
      platform: ubuntu
#  - name: ubuntu-16.04

suites:
  - name: default
#  - name: logfile
#  - name: sentinel
#  - name: checksum
#  - name: service-name
