---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 2
  require_ruby_for_busser: false
  require_chef_for_busser: true
  hosts: localhost

platforms:
  - name: ubuntu-14.04

suites:
#  - name: default
  - name: logfile
#  - name: sentinel
#  - name: checksum
#  - name: service-name
