---
- hosts: localhost
  tasks:
    - name: Replace .kitchen.yml for ansible-redis role
      copy:
        src: files/test/.kitchen.yml
        dest: vendor/davidwittman.redis/.kitchen.yml

    - name: Copy vars for testing
      copy:
        src: vars/version.yml
        dest: vendor/davidwittman.redis/vars.yml

    - name: Replace kitchen driver in Gemfile
      lineinfile:
        path: vendor/davidwittman.redis/Gemfile
        regexp: '^gem "kitchen-vagrant"'
        line: 'gem "kitchen-docker"'

    - name: enable overcommit in sysctl
      become: true
      sysctl:
        name: vm.overcommit_memory
        value: 1
        state: present
        reload: yes
        ignoreerrors: yes

    - name: Rename role
      command: " mv {{ playbook_dir }}/vendor/davidwittman.redis {{ playbook_dir }}/vendor/ansible-redis"
      when: true