---
  - name: Gather package facts
    package_facts:
      manager: "auto"

  - name: Remove OS redis packages
    become: true
    package:
      name: "{{ item }}"
      state: absent
    with_items:
      - "redis-server"
      - "redis-tools"

  - name: Set redis password from vault
    set_fact:
      redis_password: "{{ vault_catalog_db_pass }}"
    when: vault_catalog_db_pass is defined

  - name: Import ansible-redis role
    become: true
    import_role:
      name: vendor/ansible-redis

  - name: Test redis-cli
    command: "redis-cli info"
    register: redis_info
    changed_when: false
    failed_when: redis_info.stdout is not defined or "redis_version:" + redis_version not in redis_info.stdout
    ignore_errors: yes

  - name: Fail if unable to connect to redis
    fail:
      msg: "TEST FAILED: Unable to connect to redis server"
    when: redis_info.failed

  - name: Show redis info
    debug:
      msg: "{{ redis_info }}"