version: 2
jobs:
  lint:
    docker:
      # specify the version you desire here
      - image: particlekit/ansible-lint

    working_directory: ~/repo

    steps:
      - run: ansible-lint --version
      - checkout

      # Ansible Galaxy install
      - run: ansible-galaxy install -r requirements.yml -p vendor

      # Ansible syntax check
      - run: ansible-playbook --syntax-check prepare-test.yml

      # Ansible lint check
      - run: ansible-lint -v -x ANSIBLE0010 --exclude=vendor prepare-test.yml

  test-kitchen:
    machine: true
    steps:
      - checkout
      # Install ansible
      - run:
          name: Install ansible
          command: |
            sudo apt-add-repository -y ppa:ansible/ansible
            sudo add-apt-repository -y ppa:jonathonf/python-2.7
            sudo apt-get update
            sudo apt-get install -y python2.7 ansible

      # Ansible Galaxy install
      - run: ansible-galaxy install -r requirements.yml -p vendor

      # Bundle install for ansible-redis role
      - run:
          name: Install dependencies
          command: |
            cd vendor/ansible-redis
            bundle install

      # Run test kitchen for ansible-redis role
      - run:
          name: Run test-kitchen
          command: |
            cd vendor/ansible-redis
            bundle exec kitchen test

workflows:
  version: 2
  commit:
    jobs:
      - lint
      - test-kitchen:
          requires:
            - lint
