version: 2
jobs:
  test-ubuntu-1404:
    docker:
      - image: ubuntu:14.04
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install bundler
      - run:
          name: Install test-kitchen
          command: bundle install
      - run:
          name: Run test-kitchen
          command: bundle exec kitchen test test-ubuntu-1404

workflows:
  version: 2
  build:
    jobs:
      - test-ubuntu-1404
