version: 2
jobs:
  test-ubuntu-1404:
    working_directory: ~
    machine:
      ruby:
        version: 2.4
      services:
        - docker
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install bundler
      - run:
          name: Install test-kitchen
          command: bundle install
      - run:
          name: Run test-kitchen
          command: bundle exec kitchen test test-ubuntu-1404

workflows:
  version: 2
  build:
    jobs:
      - test-ubuntu-1404
